name: flutter_restaurant_store
description: Restaurant Store App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_auth_desktop: ^1.0.0
  firebase_core: ^1.18.0
  firebase_core_desktop: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.0
  flutterfire_ui: ^0.4.2
  form_field_validator: ^1.1.0
  geolocator: ^8.2.1
  geolocator_linux: ^0.1.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  hydrated_bloc: ^9.0.0-dev.2
  infinite_scroll_pagination: ^3.2.0
  injectable: ^1.5.3
  injector: ^2.0.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.1.61
  syncfusion_flutter_maps: ^20.1.61
  timeago: ^3.2.2

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  lint: ^1.8.2

flutter:
  uses-material-design: true
  generate: true
